services:
  - type: web
    name: python-whatsapp-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 run.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
